spring.application.name=embabel-sample-application

# Expose the embabel actuator endpoint
management.endpoints.web.exposure.include=health,info,embabel

# Enable the REST API and UI page controller
embabel.workflow.visualizer.enabled=true

# Planning / execution debug logs
embabel.agent.verbosity.debug=true
logging.level.com.embabel=DEBUG