const { chromium } = require('playwright');
const fs = require('fs');
const assert = require('assert/strict');
const path = require('path');
const os = require('os');
// Usage: NODE_PATH=<directory containing playwright> node visualizer.cjs <catalog.json>
// Capture a catalog from a running sample application's /embabel-workflows/api.
const catalogPath = process.argv[2];
if (!catalogPath) throw new Error('Pass a workflow catalog JSON file as the first argument.');
(async () => {
 const browser = await chromium.launch({headless:true});
 const page = await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 const html=fs.readFileSync(process.env.VISUALIZER_HTML || path.resolve(__dirname, '../../main/resources/com/patbaumgartner/embabel/workflow/visualizer/workflow-visualizer.html'),'utf8');
 await page.route('**/test/embabel-workflows', r=>r.fulfill({contentType:'text/html',body:html}));
 await page.route('**/test/embabel-workflows/api', r=>r.fulfill({contentType:'application/json',body:fs.readFileSync(catalogPath,'utf8')}));
 await page.goto('http://visualizer.test/test/embabel-workflows');
 await page.locator('.agent').first().waitFor();
 const agents=page.locator('.agent'); console.log('Agents:',await agents.count());
 const a=agents.first();
 const active=()=>a.locator('.view-panel:not([hidden])');
 const height=()=>active().locator('div.flow').evaluate(e=>e.getBoundingClientRect().height);
 const initial=await height();
 await a.getByRole('tab',{name:'Dependencies',exact:true}).click();
 assert.equal(await height(),initial,'shared initial canvas height');
 const grip=active().locator('.view-resize');
 await grip.scrollIntoViewIfNeeded();
 const r=await grip.boundingBox();
 await page.mouse.move(r.x+r.width/2,r.y+r.height/2); await page.mouse.down();
 await page.mouse.move(r.x+r.width/2,r.y+r.height/2+160,{steps:12}); await page.mouse.up();
 assert.equal(await height(),initial+160,'dragging Dependencies grows from its visible height');
 await a.getByRole('tab',{name:'Flow',exact:true}).click();
 assert.equal(await height(),initial+160,'Flow shares resized canvas');
 const checkNoOverlap=async()=>assert(await agents.evaluateAll(es=>es.every((e,i)=>i===es.length-1||e.getBoundingClientRect().bottom<=es[i+1].getBoundingClientRect().top)),'agent panels do not overlap');
 await checkNoOverlap();
 await active().locator('.view-resize').focus(); await page.keyboard.press('Home');
 assert.equal(await height(),240); await checkNoOverlap();
 await page.screenshot({path:path.join(os.tmpdir(), 'visualizer-resized.png'),fullPage:false});
 await active().getByRole('button',{name:/Zoom In/}).click();
 await active().locator('div.flow').evaluate(e=>{e.scrollLeft=500;e.scrollTop=200});
 await active().getByRole('button',{name:/Fit/}).click();
 assert.deepEqual(await active().locator('div.flow').evaluate(e=>[e.scrollLeft,e.scrollTop]),[0,0]);
 // Move a node outside its original extent, then fit: all cards remain inside the viewport.
 const node=active().locator('.node-g').first(); await node.focus();
 for(let i=0;i<15;i++) await page.keyboard.press('Shift+ArrowDown');
 await active().getByRole('button',{name:/Fit/}).click();
 assert(await active().locator('div.flow').evaluate(e=>{const v=e.getBoundingClientRect();return [...e.querySelectorAll('.node-g')].every(n=>{const r=n.getBoundingClientRect();return r.left>=v.left&&r.right<=v.right&&r.top>=v.top&&r.bottom<=v.bottom})}),'Fit includes moved nodes');
 await active().getByRole('button',{name:/Reset Layout/}).click();
 await page.setViewportSize({width:390,height:844});
 await a.scrollIntoViewIfNeeded();
 await checkNoOverlap();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no mobile page overflow');
 await page.screenshot({path:path.join(os.tmpdir(), 'visualizer-mobile.png'),fullPage:false});
 await page.setViewportSize({width:1440,height:1000});
 await a.scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(os.tmpdir(), 'visualizer-desktop.png'),fullPage:false});
 assert.deepEqual(errors,[],'no browser errors');
 console.log('PASS: shared sizing, Dependencies drag, tab switch, keyboard resize, overlap, zoom/fit/reset, moved-node fit, mobile, context path');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
